### ISSUE TITLE
problem about acc1

### ISSUE THREAD

**Issue by Li-brua** [HanGyojin/RLB-MI#1]
Hello, In your paper, is the calculation of acc1 also calculated according to the attack of 100 IDs in the code? I use the DWGGAN trained by celeba exposed by Brep-MI, that is, the same GAN as you, one is the one you disclose and the other is Brep-MI public, but the paper mentions the same weight, to attack the VGG trained by celeba private training data, VGG is also disclosed with Brep-MI, acc1 is more than 30%, and the experimental results in your paper are more than 60%, what is wrong with me? Is it a problem caused by the small number of attack identities 100? Is it too long to attack 300 identities like Brep-MI?

**Comment by HanGyojin** [comment]
Thanks for leaving the issue. Below are answers to your questions.

1. We attacked all 1000 identities for the results in the paper. 
2. We realized that we made some mistakes in the process of cleaning up the code. The code was updated.
3. We have provided code to experiment with on a single gpu. Using multiple GPUs with some code modifications will allow you to experiment faster.
